spring:
  application:
    name: buy-rest
  cloud:
    consul:
      host: 192.168.99.103
      port: 8500
server:
  port: 8286
com:
  alipay:
    sofa:
      rpc:
        bolt-port: 12224
        registry:
          address: consul://192.168.99.103:8500?healthCheck.type=http&healthCheck.path=/actuator/readiness&healthCheck.port=${server.port}
      tracer:
        zipkin:
          base-url: http://192.168.99.108:9411
logging:
  graylog:
    host: 192.168.99.108
    port: 12201
env: dev
